### ISSUE TITLE
Error during start-up using daemon on Ubuntu

### ISSUE THREAD

**Issue by astjohn** [SharkHunter/Channel#15]
Does this plugin work on a linux server?

Thanks!

```
[main] DEBUG 19:40:20.338 launching: mplayer
[main] INFO  19:40:20.363 Done!
[main] INFO  19:40:20.377 Searching for plugins in /usr/share/pms-linux/plugins
[main] INFO  19:40:20.378 Found plugin: com.sharkhunter.channel.CH_plugin
[main] INFO  19:40:20.393 Start channel 1.42
[main] INFO  19:40:20.398 parsing channel file /usr/share/pms-linux/channels/navix.ch version 0.30
[main] INFO  19:40:20.399 Configuration error: children
[main] INFO  19:40:20.531 Exception in thread "main" java.awt.HeadlessException: 
[main] INFO  19:40:20.532 No X11 DISPLAY variable was set, but this program performed an operation which requires it.
[main] INFO  19:40:20.532   at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:173)
[main] INFO  19:40:20.532   at java.awt.Window.<init>(Window.java:437)
[main] INFO  19:40:20.532   at java.awt.Frame.<init>(Frame.java:419)
[main] INFO  19:40:20.532   at java.awt.Frame.<init>(Frame.java:384)
[main] INFO  19:40:20.532   at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1758)
[main] INFO  19:40:20.532   at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1835)
[main] INFO  19:40:20.533   at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1692)
[main] INFO  19:40:20.533   at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:864)
[main] INFO  19:40:20.533   at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:668)
[main] INFO  19:40:20.533   at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:639)
[main] INFO  19:40:20.533   at net.pms.PMS.main(PMS.java:1011)
```

**Comment by SharkHunter** [comment]
This look s like a generic PMS error as Channels doesn't do anything to the PMS GUI. 
This indicates that PMS does some updating of it's GUI something Channels is unaware of.
"main] INFO  19:40:20.533   at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:639)
[main] INFO  19:40:20.533   at net.pms.PMS.main(PMS.java:1011)"

**Comment by skeptical** [comment]
Channel just happens to be the first plugin being loaded here, I think, and PMS is misconfigured to be in GUI mode. I've never tried headless mode myself, but have a look at the instructions here under "How to run PS3 Media Server in headless mode as service / daemon (easy guide)"
http://www.ps3mediaserver.org/forum/viewtopic.php?f=3&t=13046

**Comment by astjohn** [comment]
@SharkHunter, @skeptical, Thanks!  I've been running headless for about 2 years now, but haven't updated in a while.  I noticed there were now some packages for Ubuntu, which I'm using, so perhaps I'll wipe it clean and try fresh with one of those.  Cheers.
