### ISSUE TITLE
Problem installing plugin

### ISSUE THREAD

**Issue by monostop** [SharkHunter/Channel#19]
I use PMS 1.90.1. I have downloaded the jar file and put in my plugins folder. I don't get the channels to show up under plugins and the following is in the log. Any idea whats up?

ERROR 2014-06-28 18:49:18.185 [main] Error instantiating plugin
java.lang.NoSuchMethodError: net.pms.PMS.isWindows()Z
    at com.sharkhunter.channel.ChannelCfg.init(ChannelCfg.java:246) ~[na:na]
    at com.sharkhunter.channel.CH_plugin.<init>(CH_plugin.java:44) ~[na:na]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.7.0_25]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_25]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:1.7.0_25]
    at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:1.7.0_25]
    at java.lang.Class.newInstance(Unknown Source) ~[na:1.7.0_25]
    at net.pms.external.ExternalFactory.instantiateLateListeners(ExternalFactory.java:230) ~[pms.jar:1.90.1]
    at net.pms.PMS.init(PMS.java:540) ~[pms.jar:1.90.1]
    at net.pms.PMS.createInstance(PMS.java:872) ~[pms.jar:1.90.1]
    at net.pms.PMS.main(PMS.java:949) ~[pms.jar:1.90.1]

**Comment by SharkHunter** [comment]
PMS has removed the function isWindows which Channels relies on. Channels has evolved since and uses a whole bunch of new features in UMS which means it will be very hard to fix this. 
The easy solution is to use UMS instead:
http://www.universalmediaserver.com/forum/index.php

**Comment by monostop** [comment]
I installed UMS and everything worked straight out of the box! Thanks for the work you put in this project!
